export default {
  LOAD_BEERS: 'LOAD_BEERS',
  FILTER_BEERS: 'FILTER_BEERS',

  LOAD_RANDOM_BEER: 'LOAD_RANDOM_BEER',
  LOAD_RANDOM_NON_ALCOHOLIC_BEER: 'LOAD_RANDOM_NON_ALCOHOLIC_BEER',

  API_ERROR: 'API_ERROR',
};
